/**
 * EquiVault API - the bridge between the compiled Compact contract and any
 * front end (web UI, CLI, tests).
 *
 * The important property of this layer: it holds the user's private state and
 * never transmits it. Requests are sealed locally, proofs are generated by the
 * user's own proof server, and only the proof plus the public outputs go to the
 * network.
 *
 * @packageDocumentation
 */

import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { toHex } from '@midnight-ntwrk/midnight-js-utils';
import { type Observable, combineLatest, from, map } from 'rxjs';

import {
  DOMAIN,
  EquiVaultContract,
  type EquiVaultPrivateState,
  type SealedRequest,
  allocationFor,
  createEquiVaultPrivateState,
  domainTag,
  ledger as readLedger,
  oversubscriptionBps,
  Phase,
  pureCircuits,
  randomBytes,
} from '@equivault/contract';

import {
  type DeployedEquiVaultContract,
  type EquiVaultContractType,
  type EquiVaultDerivedState,
  type EquiVaultProviders,
  type OfferingPublicState,
  type ViewerState,
  equiVaultPrivateStateKey,
} from './common-types.js';

/**
 * Minimal structural logger, so this package does not force a logging library
 * on its consumers. `pino` satisfies it as-is.
 */
export type Logger = {
  info: (obj: unknown) => void;
  trace: (obj: unknown) => void;
};

export * from './common-types.js';
export * from './errors.js';
export * from './verification.js';

export type CreateOfferingParams = {
  name: string;
  description: string;
  /** e.g. 'shares', 'scholarships', 'tickets'. */
  unit: string;
  totalSupply: bigint;
  unitPriceCents: bigint;
  minRequest: bigint;
  maxRequest: bigint;
  /** Unix seconds. */
  subscriptionDeadline: bigint;
};

export interface DeployedEquiVaultAPI {
  readonly contractAddress: ContractAddress;
  readonly state$: Observable<EquiVaultDerivedState>;

  submitRequest: (amount: bigint) => Promise<void>;
  closeSubscription: () => Promise<void>;
  finalizeAllocation: () => Promise<void>;
  claimAllocation: () => Promise<bigint>;
}

export class EquiVaultAPI implements DeployedEquiVaultAPI {
  readonly contractAddress: ContractAddress;
  readonly state$: Observable<EquiVaultDerivedState>;

  private constructor(
    public readonly deployedContract: DeployedEquiVaultContract,
    private readonly providers: EquiVaultProviders,
    private readonly logger?: Logger,
  ) {
    this.contractAddress = deployedContract.deployTxData.public.contractAddress;
    providers.privateStateProvider.setContractAddress(this.contractAddress);

    this.state$ = combineLatest(
      [
        providers.publicDataProvider
          .contractStateObservable(this.contractAddress, { type: 'latest' })
          .pipe(map((contractState) => readLedger(contractState.data))),
        from(
          providers.privateStateProvider.get(equiVaultPrivateStateKey) as Promise<EquiVaultPrivateState>,
        ),
      ],
      (ledger, privateState) => EquiVaultAPI.deriveState(ledger, privateState),
    );
  }

  /**
   * Combines public ledger state with the viewer's private state.
   *
   * Note what is happening here: `hasSubmitted` is answered by hashing the
   * user's own secret key into the offering-scoped nullifier and asking the
   * public set whether it contains that hash. The chain never learns who asked.
   */
  static deriveState(
    ledger: ReturnType<typeof readLedger>,
    privateState: EquiVaultPrivateState | undefined,
  ): EquiVaultDerivedState {
    const publicState: OfferingPublicState = {
      offeringId: toHex(ledger.offeringId),
      name: ledger.resourceName,
      description: ledger.resourceDescription,
      unit: ledger.resourceUnit,
      totalSupply: ledger.totalSupply,
      unitPriceCents: ledger.unitPriceCents,
      minRequest: ledger.minRequest,
      maxRequest: ledger.maxRequest,
      subscriptionDeadline: ledger.subscriptionDeadline,
      allocationRule: ledger.allocationRule,
      phase: ledger.phase,
      participantCount: ledger.participantCount,
      claimCount: ledger.claimCount,
      totalDemand: ledger.totalDemand,
      allocatedTotal: ledger.allocatedTotal,
      issuerCommitment: toHex(ledger.issuerCommitment),
      requestTreeRoot: ledger.requestTree.root().toString(),
    };

    const viewer = EquiVaultAPI.deriveViewerState(ledger, privateState);

    return {
      ...publicState,
      viewer,
      oversubscriptionBps: oversubscriptionBps(ledger.totalSupply, ledger.totalDemand),
    };
  }

  private static deriveViewerState(
    ledger: ReturnType<typeof readLedger>,
    privateState: EquiVaultPrivateState | undefined,
  ): ViewerState {
    if (privateState === undefined) {
      return { isIssuer: false, hasSubmitted: false, hasClaimed: false };
    }

    const { offeringId, secretKey } = { offeringId: ledger.offeringId, secretKey: privateState.secretKey };
    const tagFor = (domain: string): Uint8Array =>
      pureCircuits.identityTag(offeringId, secretKey, domainTag(domain));

    const submitNullifier = tagFor(DOMAIN.submit);
    const claimNullifier = tagFor(DOMAIN.claim);
    const issuerTag = tagFor(DOMAIN.issuer);

    const hasClaimed = ledger.claimNullifiers.member(claimNullifier);
    const myRequest = privateState.request?.amount;

    return {
      isIssuer: toHex(issuerTag) === toHex(ledger.issuerCommitment),
      hasSubmitted: ledger.submissionNullifiers.member(submitNullifier),
      hasClaimed,
      myRequest,
      myAllocation: hasClaimed ? ledger.allocationReceipts.lookup(claimNullifier) : undefined,
      projectedAllocation:
        myRequest !== undefined && ledger.totalDemand > 0n
          ? allocationFor(myRequest, ledger.totalSupply, ledger.totalDemand)
          : undefined,
    };
  }

  // --- transactions --------------------------------------------------------

  /**
   * Seals a request into local private state, then proves and submits it.
   *
   * The amount is written to the private state provider FIRST, because the
   * witness functions read it from there while the proof is generated. It is
   * never included in the transaction.
   */
  async submitRequest(amount: bigint): Promise<void> {
    const sealed: SealedRequest = { amount, nonce: randomBytes(32) };
    const current = await this.requirePrivateState();
    await this.providers.privateStateProvider.set(equiVaultPrivateStateKey, {
      ...current,
      request: sealed,
    });

    this.logger?.info({ submitRequest: { sealed: true } });

    try {
      const txData = await this.deployedContract.callTx.submitRequest();
      this.logger?.trace({
        transactionAdded: { circuit: 'submitRequest', txHash: txData.public.txHash },
      });
    } catch (error) {
      // Roll the sealed request back so the UI does not claim a subscription
      // that never settled.
      await this.providers.privateStateProvider.set(equiVaultPrivateStateKey, current);
      throw error;
    }
  }

  async closeSubscription(): Promise<void> {
    const state = await this.latestLedger();
    if (state.phase !== Phase.OPEN) {
      throw new Error('EquiVault: this offering is not open');
    }

    const nowSeconds = BigInt(Math.floor(Date.now() / 1000));
    const deadlinePassed = nowSeconds >= state.subscriptionDeadline;

    // Prefer the permissionless path once the deadline has passed, so a
    // non-issuer can also close a stale offering.
    const txData = deadlinePassed
      ? await this.deployedContract.callTx.closeSubscriptionAfterDeadline()
      : await this.deployedContract.callTx.closeSubscriptionAsIssuer();

    this.logger?.trace({
      transactionAdded: { circuit: 'closeSubscription', txHash: txData.public.txHash },
    });
  }

  async finalizeAllocation(): Promise<void> {
    const txData = await this.deployedContract.callTx.finalizeAllocation();
    this.logger?.trace({
      transactionAdded: { circuit: 'finalizeAllocation', txHash: txData.public.txHash },
    });
  }

  async claimAllocation(): Promise<bigint> {
    const txData = await this.deployedContract.callTx.claimAllocation();
    this.logger?.trace({
      transactionAdded: { circuit: 'claimAllocation', txHash: txData.public.txHash },
    });
    return txData.private.result;
  }

  // --- deployment ----------------------------------------------------------

  static async deploy(
    providers: EquiVaultProviders,
    params: CreateOfferingParams,
    logger?: Logger,
  ): Promise<EquiVaultAPI> {
    logger?.info({ deployOffering: { name: params.name } });

    const deployed = await deployContract(providers, {
      compiledContract: EquiVaultContract,
      privateStateId: equiVaultPrivateStateKey,
      initialPrivateState: createEquiVaultPrivateState(randomBytes(32)),
      args: [
        randomBytes(32),
        params.name,
        params.description,
        params.unit,
        params.totalSupply,
        params.unitPriceCents,
        params.minRequest,
        params.maxRequest,
        params.subscriptionDeadline,
      ],
    });

    return new EquiVaultAPI(deployed, providers, logger);
  }

  static async join(
    providers: EquiVaultProviders,
    contractAddress: ContractAddress,
    logger?: Logger,
  ): Promise<EquiVaultAPI> {
    logger?.info({ joinOffering: { contractAddress } });

    const deployed = await findDeployedContract<EquiVaultContractType>(providers, {
      contractAddress,
      compiledContract: EquiVaultContract,
      privateStateId: equiVaultPrivateStateKey,
      initialPrivateState: await EquiVaultAPI.resolvePrivateState(providers, contractAddress),
    });

    return new EquiVaultAPI(deployed, providers, logger);
  }

  // --- private state -------------------------------------------------------

  /**
   * Loads this contract's private state, minting a fresh secret key the first
   * time the user encounters this offering.
   */
  private static async resolvePrivateState(
    providers: EquiVaultProviders,
    contractAddress: ContractAddress,
  ): Promise<EquiVaultPrivateState> {
    providers.privateStateProvider.setContractAddress(contractAddress);
    const existing = await providers.privateStateProvider.get(equiVaultPrivateStateKey);
    return existing ?? createEquiVaultPrivateState(randomBytes(32));
  }

  private async requirePrivateState(): Promise<EquiVaultPrivateState> {
    const state = await this.providers.privateStateProvider.get(equiVaultPrivateStateKey);
    if (state === null || state === undefined) {
      throw new Error('EquiVault: no private state for this offering');
    }
    return state;
  }

  private async latestLedger(): Promise<ReturnType<typeof readLedger>> {
    const contractState = await this.providers.publicDataProvider.queryContractState(
      this.contractAddress,
    );
    if (contractState === null) {
      throw new Error('EquiVault: offering not found on this network');
    }
    return readLedger(contractState.data);
  }
}
