/**
 * The single interface every screen talks to.
 *
 * Both backends implement it:
 *   - `LiveOfferingSession`  - real Midnight transactions, real proofs, real ledger.
 *   - `DemoOfferingSession`  - the real compiled circuits run locally against an
 *                              in-memory ledger, with no network and no wallet.
 *
 * Because the screens only see this interface, Demo Mode exercises exactly the
 * same UI, the same allocation rule and the same contract assertions as the
 * live product. What differs is stated plainly in `capabilities`.
 *
 * @module
 */

import type { EquiVaultDerivedState } from '@equivault/api';

export type SessionMode = 'demo' | 'live';

/**
 * An honest statement of what a given backend actually does. The UI reads these
 * flags rather than hardcoding claims, so a badge can never assert something
 * the backend did not do.
 */
export type SessionCapabilities = {
  /** Circuit assertions, nullifiers and Merkle membership are really enforced. */
  readonly executesRealCircuits: boolean;
  /** A zero-knowledge proof is generated by a proof server. */
  readonly generatesZkProofs: boolean;
  /** Transactions are verified by Midnight consensus and recorded on a ledger. */
  readonly settlesOnChain: boolean;
};

export const DEMO_CAPABILITIES: SessionCapabilities = {
  executesRealCircuits: true,
  generatesZkProofs: false,
  settlesOnChain: false,
};

export const LIVE_CAPABILITIES: SessionCapabilities = {
  executesRealCircuits: true,
  generatesZkProofs: true,
  settlesOnChain: true,
};

export type OfferingSession = {
  readonly address: string;
  readonly mode: SessionMode;
  readonly capabilities: SessionCapabilities;

  /** Current derived state (public ledger + this viewer's private view). */
  getState: () => EquiVaultDerivedState;
  subscribe: (listener: (state: EquiVaultDerivedState) => void) => () => void;

  submitRequest: (amount: bigint) => Promise<void>;
  closeSubscription: () => Promise<void>;
  finalizeAllocation: () => Promise<bigint | void>;
  claimAllocation: () => Promise<bigint>;
};

/** A tiny observable, so the demo backend needs no extra dependencies. */
export class StateStore<T> {
  private listeners = new Set<(value: T) => void>();

  constructor(private value: T) {}

  get(): T {
    return this.value;
  }

  set(next: T): void {
    this.value = next;
    for (const listener of this.listeners) {
      listener(next);
    }
  }

  subscribe(listener: (value: T) => void): () => void {
    this.listeners.add(listener);
    listener(this.value);
    return () => {
      this.listeners.delete(listener);
    };
  }
}
